# Generated by Django 2.2.2 on 2019-07-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ('sort_order',)},
        ),
    ]
