# Generated by Django 2.2.2 on 2019-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
