# Generated by Django 2.2.2 on 2019-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190814_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
