# Generated by Django 2.2.2 on 2019-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190607_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='colors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
