# Generated by Django 2.2.2 on 2019-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190810_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
