# Generated by Django 2.2.2 on 2019-08-10 20:14

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190810_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
