# Generated by Django 2.2.2 on 2019-08-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190810_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('total_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('detail', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
