# Generated by Django 2.2.2 on 2019-08-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190816_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='country',
            field=models.CharField(blank=True, default='us', max_length=20),
        ),
    ]
