# Generated by Django 2.2.2 on 2019-08-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190816_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
            ],
        ),
    ]
