# Generated by Django 2.2.2 on 2019-08-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_shippingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingoption',
            name='business_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
