# Generated by Django 2.2.2 on 2019-08-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190817_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('template', 'Predefined Template'), ('custom', 'Custom Design')], max_length=30, null=True),
        ),
    ]
