# Generated by Django 2.2.2 on 2019-08-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('submitted', 'Submitted'), ('proof', 'Awaiting customer approval'), ('approved', 'Approved'), ('production', 'In production'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='open', max_length=30),
        ),
    ]
