# Generated by Django 2.2.2 on 2019-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190820_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_status_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
