# Generated by Django 2.2.2 on 2019-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190821_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_fingerprint',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
