# Generated by Django 2.2.2 on 2019-08-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_project_client_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_fingerprint',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
