# Generated by Django 2.2.2 on 2019-08-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190822_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-date_created',)},
        ),
    ]
