# Generated by Django 2.2.2 on 2019-08-31 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_default_template'),
        ('orders', '0021_auto_20190829_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Paper'),
        ),
        migrations.AddField(
            model_name='design',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Pattern'),
        ),
    ]
