# Generated by Django 2.2.2 on 2019-09-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('left', models.IntegerField(blank=True, default=0, null=True)),
                ('top', models.IntegerField(blank=True, default=0, null=True)),
                ('angle', models.IntegerField(blank=True, default=0, null=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Design')),
            ],
        ),
    ]
