# Generated by Django 2.2.2 on 2019-09-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20190917_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designelement',
            old_name='scaleX',
            new_name='scale_x',
        ),
        migrations.RenameField(
            model_name='designelement',
            old_name='scaleY',
            new_name='scale_y',
        ),
    ]
