# Generated by Django 2.2.2 on 2019-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='collapsibility',
            field=models.CharField(choices=[('c', 'Collapsible'), ('nc', 'Non-collapsible')], default='c', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rigidity',
            field=models.CharField(choices=[('rigid', 'Rigid Boxes'), ('folding', 'Folding Boxes')], default='rigid', max_length=40),
        ),
    ]
