# Generated by Django 2.2.2 on 2019-06-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rigid', 'Rigid Boxes'), ('setup', 'Setup Boxes')], default='rigid', max_length=40),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('preset', 'Preset'), ('custom', 'Custom')], default='preset', max_length=40),
        ),
    ]
