# Generated by Django 2.2.2 on 2019-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190712_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rigidity',
            field=models.CharField(choices=[('rigid', 'Rigid'), ('folding', 'Folding')], default='rigid', max_length=40),
        ),
    ]
