# Generated by Django 2.2.2 on 2019-07-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rigidity',
            field=models.CharField(choices=[('rigid', 'Rigid box'), ('folding', 'Folding box')], default='rigid', max_length=40),
        ),
    ]
