# Generated by Django 2.2.2 on 2019-07-12 22:12

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190712_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('sort_order',), 'verbose_name_plural': 'product categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='picture',
            field=models.ImageField(blank=True, height_field='picture_height', upload_to=products.models.get_product_image_path, width_field='picture_width'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='picture_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='picture_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
