# Generated by Django 2.2.2 on 2019-07-28 14:02

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('picture', models.ImageField(blank=True, height_field='picture_height', upload_to=products.models.get_paper_image_path, width_field='picture_width')),
                ('picture_width', models.IntegerField(blank=True, null=True)),
                ('picture_height', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('picture', models.ImageField(blank=True, height_field='picture_height', upload_to=products.models.get_pattern_image_path, width_field='picture_width')),
                ('picture_width', models.IntegerField(blank=True, null=True)),
                ('picture_height', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='products.Product'),
        ),
    ]
