# Generated by Django 2.2.2 on 2019-08-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190728_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_products', to='products.Template'),
        ),
    ]
